#!/bin/bash
set -eu -o pipefail

echo "+++ Running Hawkeye"
SCAN_LOG=$(docker run --rm -v "$PWD:/target" stono/hawkeye)
SEARCH_STRING="[info] Doing writer: console"
SCAN_RESULTS="${SCAN_LOG#${SEARCH_STRING}*}"

echo "+++ Scan results"
echo "${SCAN_RESULTS}"
